---
title       : BMI & Daily Calories Requirement
subtitle    : A simple calculator
author      : Oliver Rojas
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]     # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## BMI & Daily Calories Requirement

This product is a simple calculator who compute your Body Mass Index (BMI) and your Daily Calories Requirement based in Harris-Benedict equation develop in 1918. In this case we use the revision made by Mifflin & St. Jeor (1990) who ajust the over stimation made by the original equation.

You can find more information in the next links:

* http://www.ncbi.nlm.nih.gov/pubmed/2305711
* https://en.wikipedia.org/wiki/Harris-Benedict_equation

You can access in github



--- .class #1

## Input data

The calculator use the next input data:

* Age (in Years)
* Weight (in Kilograms)
* Height (in Centimeters)
* Gender
* Physical activity

Whit this data we also will calculate your BMI and tell you about what category you have according the World Health Organization.

--- .class #1

## Boddy Mass Index

The Body Mass Index (BMI) is a value derived from weight & height. It's an attempt to quantify the amount of tissue mass and categorize into four categories: Underweight, Normal Weight, Over Weight and Obese. Nevertheless the simplicity of the formula it's a very good predictor of your nutritional status.

The calculations and categories are:

$$ BMI=\frac { Weight(kg) }{ Height({ m }^{ 2 }) } $$

1. Underweight (< 18.5)
2. Normal weight (18.5 - 24.9)
3. Over weight (25 - 29.9)
4. Obese (> 30)

--- .class #1

## Harris-Benedict equation

With your BMI already calculated we also use the Harris-Benedict equation to compute your calories requirement. This algorithm mix your age, gender and physical activity in order to get a very close look in your energy daily requirements. First we need to calculate your Basal Metabolic Rate (BMR).

 $$ maleBMR=(10\cdot weight)+(6.25\cdot height)-(5\cdot age)+5 $$
 $$ femaleBMR=(10\cdot weight)+(6.25\cdot height)-(5\cdot age)-161 $$

And then multiply your BMR with a factor derived of your phisical activity.

* Little to None excercise:                   $Calories=BMR\times 1.2$
* Ligth excercise, 1-3 days per week:         $Calories=BMR\times 1.375$
* Moderate excercise, 3-5 days per week:      $Calories=BMR\times 1.55$
* Heavy exercise, 6-7 days per week:          $Calories=BMR\times 1.725$
* Very heavy exercise (extra heavy workouts): $Calories=BMR\times 1.9$